#!/usr/bin/env bats
# tests/test_doctor.bats — Tests for lib/doctor.sh health checks

load 'helpers/setup'

setup() {
  setup_sandbox
  export DEVTERM_ROOT
  export DEVTERM_OS="macos"
  source "$DEVTERM_ROOT/lib/utils.sh"
  source "$DEVTERM_ROOT/lib/doctor.sh"
}

teardown() {
  teardown_sandbox
}

# ── check_config_files ─────────────────────────────────────────────────────

@test "check_config_files reports missing .zshrc" {
  run check_config_files
  # Should mention .zshrc regardless of whether it exists
  assert_output_contains ".zshrc"
}

@test "check_config_files detects existing .zshrc" {
  echo "# test zshrc" > "$HOME/.zshrc"
  # Also create OMZ dir so the function's OMZ check doesn't cause exit 1
  mkdir -p "$HOME/.oh-my-zsh"
  run check_config_files
  assert_output_contains ".zshrc"
  assert_success
}

@test "check_config_files recognises devterm-generated .zshrc" {
  echo "# generated by devterm" > "$HOME/.zshrc"
  run check_config_files
  assert_output_contains "Generated by devterm"
}

@test "check_config_files reports missing starship.toml as warning (not error)" {
  echo "# test" > "$HOME/.zshrc"
  run check_config_files
  # starship.toml missing is a warning, not a hard failure
  assert_output_contains "starship.toml"
}

@test "check_config_files detects existing starship.toml" {
  echo "# test" > "$HOME/.zshrc"
  mkdir -p "$HOME/.config"
  echo 'palette = "catppuccin_mocha"' > "$HOME/.config/starship.toml"
  # Also create OMZ dir so the function's OMZ check doesn't cause exit 1
  mkdir -p "$HOME/.oh-my-zsh"
  run check_config_files
  assert_output_contains "starship.toml"
  assert_success
}

# ── check_tools ────────────────────────────────────────────────────────────

@test "check_tools detects git as present" {
  run check_tools
  assert_output_contains "git"
}

@test "check_tools detects zsh as present" {
  run check_tools
  assert_output_contains "zsh"
}

@test "check_tools reports starship as required tool" {
  run check_tools
  assert_output_contains "starship"
}

# ── check_environment ──────────────────────────────────────────────────────

@test "check_environment runs without crashing" {
  run check_environment
  [[ "$status" -le 1 ]] || { echo "Unexpected exit code: $status"; return 1; }
}

@test "check_environment reports architecture" {
  run check_environment
  assert_output_contains "Architecture"
}

# ── doctor (full run) ──────────────────────────────────────────────────────

@test "doctor output contains 'devterm doctor' header" {
  run doctor
  assert_output_contains "doctor"
}

@test "doctor output contains platform info" {
  run doctor
  assert_output_contains "Platform"
}

@test "doctor exits with 0 or 1 — never crashes with unhandled error" {
  echo "# generated by devterm" > "$HOME/.zshrc"
  run doctor
  [[ "$status" -le 1 ]] || { echo "Unexpected exit code: $status"; return 1; }
}

@test "doctor returns 1 when critical tools are missing" {
  # In the sandbox, starship won't be installed
  run doctor
  # Can be 0 or 1, but must be <= 1 (no unhandled crash)
  [[ "$status" -le 1 ]] || return 1
}

# ── check_p10k_leftovers ───────────────────────────────────────────────────

@test "check_p10k_leftovers produces no output when no p10k files exist" {
  # Sandbox has a clean HOME — no p10k artifacts
  run check_p10k_leftovers
  assert_success
  # No warning section header should appear
  [[ "$output" != *"Powerlevel10k"* ]] || {
    echo "Unexpected p10k section printed in clean environment"
    return 1
  }
}

@test "check_p10k_leftovers warns when ~/.p10k.zsh exists" {
  touch "$HOME/.p10k.zsh"
  run check_p10k_leftovers
  assert_output_contains ".p10k.zsh"
}

@test "check_p10k_leftovers warns when powerlevel10k theme directory exists" {
  mkdir -p "$HOME/.oh-my-zsh/custom/themes/powerlevel10k"
  run check_p10k_leftovers
  assert_output_contains "powerlevel10k"
}

@test "check_p10k_leftovers warns when p10k instant-prompt cache exists" {
  mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}"
  touch "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-testuser.zsh"
  run check_p10k_leftovers
  assert_output_contains "instant-prompt"
}

@test "check_p10k_leftovers provides rm cleanup commands when leftovers found" {
  touch "$HOME/.p10k.zsh"
  run check_p10k_leftovers
  # Should suggest rm command so the developer knows what to do
  assert_output_contains "rm"
}

@test "check_p10k_leftovers never increments doctor issue count (informational only)" {
  # Create all three p10k artifacts
  touch "$HOME/.p10k.zsh"
  mkdir -p "$HOME/.oh-my-zsh/custom/themes/powerlevel10k"
  mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}"
  touch "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-user.zsh"

  # check_p10k_leftovers should always return 0 — it is info only, not an error
  run check_p10k_leftovers
  assert_success
}
