#!/usr/bin/env bats
# tests/test_zshrc.bats — Tests for lib/zshrc.sh (split .zshrc generation)

load 'helpers/setup'

setup() {
  setup_sandbox
  export DEVTERM_ROOT
  export DEVTERM_THEME="mocha"
  export DEVTERM_MODE="full"
  export DEVTERM_OS="macos"
  source "$DEVTERM_ROOT/lib/utils.sh"
  source "$DEVTERM_ROOT/lib/zshrc.sh"
}

teardown() {
  teardown_sandbox
}

# ── Scenario A: Fresh install ─────────────────────────────────────────────

@test "scenario A — creates all 3 files on fresh install" {
  run generate_zshrc
  assert_success
  assert_file_exists "$HOME/.zshrc"
  assert_file_exists "$HOME/.zshrc.devterm"
  assert_file_exists "$HOME/.zshrc.local"
}

@test "scenario A — loader contains 'Managed by devterm' marker" {
  generate_zshrc
  assert_file_contains "$HOME/.zshrc" "Managed by devterm"
}

@test "scenario A — loader sources .zshrc.devterm" {
  generate_zshrc
  assert_file_contains "$HOME/.zshrc" ".zshrc.devterm"
}

@test "scenario A — loader sources .zshrc.local" {
  generate_zshrc
  assert_file_contains "$HOME/.zshrc" ".zshrc.local"
}

@test "scenario A — .zshrc.local is a template (not empty)" {
  generate_zshrc
  [[ -s "$HOME/.zshrc.local" ]] || { echo "~/.zshrc.local is empty"; return 1; }
  assert_file_contains "$HOME/.zshrc.local" "personal shell customizations"
}

# ── Scenario B: Old monolithic devterm .zshrc ─────────────────────────────

@test "scenario B — backs up old monolithic .zshrc" {
  echo "# Generated by devterm — old format" > "$HOME/.zshrc"
  generate_zshrc
  local backups=("$HOME"/.zshrc.backup.*)
  [[ ${#backups[@]} -ge 1 ]] || { echo "No backup created"; return 1; }
  grep -q "Generated by devterm" "${backups[0]}" || { echo "Backup missing original content"; return 1; }
}

@test "scenario B — creates loader + local after migration" {
  echo "# Generated by devterm — old format" > "$HOME/.zshrc"
  generate_zshrc
  assert_file_contains "$HOME/.zshrc" "Managed by devterm"
  assert_file_exists "$HOME/.zshrc.local"
  assert_file_exists "$HOME/.zshrc.devterm"
}

# ── Scenario C: Already migrated ──────────────────────────────────────────

@test "scenario C — only regenerates .zshrc.devterm" {
  # Set up already-migrated state
  echo "# Managed by devterm" > "$HOME/.zshrc"
  echo "# my custom stuff" > "$HOME/.zshrc.local"
  echo "# old devterm config" > "$HOME/.zshrc.devterm"

  generate_zshrc

  # Loader must NOT be overwritten
  assert_file_contains "$HOME/.zshrc" "Managed by devterm"
  # .zshrc.local must NOT be overwritten
  assert_file_contains "$HOME/.zshrc.local" "my custom stuff"
  # .zshrc.devterm MUST be regenerated (new content)
  assert_file_contains "$HOME/.zshrc.devterm" "starship init zsh"
}

# ── Scenario D: Non-devterm .zshrc ────────────────────────────────────────

@test "scenario D — moves non-devterm .zshrc to .zshrc.local" {
  echo "# my hand-crafted zshrc with custom stuff" > "$HOME/.zshrc"
  generate_zshrc
  # Original config should now be in .zshrc.local
  assert_file_contains "$HOME/.zshrc.local" "hand-crafted"
  # Loader should be installed
  assert_file_contains "$HOME/.zshrc" "Managed by devterm"
}

@test "scenario D — does not clobber existing .zshrc.local" {
  echo "# my hand-crafted zshrc" > "$HOME/.zshrc"
  echo "# precious local config" > "$HOME/.zshrc.local"
  generate_zshrc
  # .zshrc.local must still have original content (not overwritten)
  assert_file_contains "$HOME/.zshrc.local" "precious local config"
  # The old .zshrc should be backed up instead
  local backups=("$HOME"/.zshrc.backup.*)
  [[ ${#backups[@]} -ge 1 ]] || { echo "No backup created"; return 1; }
}

# ── .zshrc.devterm content checks ─────────────────────────────────────────

@test "generated .zshrc.devterm initialises Starship" {
  generate_zshrc
  assert_file_contains "$HOME/.zshrc.devterm" "starship init zsh"
}

@test "generated .zshrc.devterm does NOT reference powerlevel10k theme" {
  generate_zshrc
  run grep "powerlevel10k/powerlevel10k" "$HOME/.zshrc.devterm"
  assert_failure
}

@test "generated .zshrc.devterm sets ZSH_THEME to empty string" {
  generate_zshrc
  assert_file_contains "$HOME/.zshrc.devterm" 'ZSH_THEME=""'
}

@test "generated .zshrc.devterm sources oh-my-zsh" {
  generate_zshrc
  assert_file_contains "$HOME/.zshrc.devterm" "oh-my-zsh.sh"
}

@test "generated .zshrc.devterm includes git aliases" {
  generate_zshrc
  assert_file_contains "$HOME/.zshrc.devterm" 'alias gs='
}

@test "generated .zshrc.devterm includes eza aliases" {
  generate_zshrc
  assert_file_contains "$HOME/.zshrc.devterm" "eza"
}

@test "generated .zshrc.devterm includes Gradle aliases for Spartan stack" {
  generate_zshrc
  assert_file_contains "$HOME/.zshrc.devterm" "alias gwb="
}

@test "generated .zshrc.devterm sets EDITOR to code" {
  generate_zshrc
  assert_file_contains "$HOME/.zshrc.devterm" 'EDITOR="code"'
}

@test "generated .zshrc.devterm exports HOME/.local/bin to PATH" {
  generate_zshrc
  assert_file_contains "$HOME/.zshrc.devterm" '/.local/bin'
}

@test "generated .zshrc.devterm includes fzf configuration" {
  generate_zshrc
  assert_file_contains "$HOME/.zshrc.devterm" "FZF_DEFAULT_OPTS"
}

@test "generated .zshrc.devterm points zshrc alias to .zshrc.local" {
  generate_zshrc
  assert_file_contains "$HOME/.zshrc.devterm" "zshrc.local"
}

# ── Platform conditionals ─────────────────────────────────────────────────

@test "generated .zshrc.devterm on macOS includes 'macos' OMZ plugin" {
  export DEVTERM_OS="macos"
  generate_zshrc
  assert_file_contains "$HOME/.zshrc.devterm" "  macos"
}

@test "generated .zshrc.devterm on Linux excludes 'macos' OMZ plugin" {
  export DEVTERM_OS="linux"
  generate_zshrc
  run grep -E "^  macos$" "$HOME/.zshrc.devterm"
  assert_failure
}

@test "generated .zshrc.devterm on Linux still has cross-platform plugins" {
  export DEVTERM_OS="linux"
  generate_zshrc
  assert_file_contains "$HOME/.zshrc.devterm" "zsh-autosuggestions"
  assert_file_contains "$HOME/.zshrc.devterm" "zsh-syntax-highlighting"
  assert_file_contains "$HOME/.zshrc.devterm" "git"
}

@test "generated .zshrc.devterm wraps flush-dns in Darwin conditional" {
  generate_zshrc
  assert_file_contains "$HOME/.zshrc.devterm" 'uname.*Darwin'
  assert_file_contains "$HOME/.zshrc.devterm" "flush-dns"
}

@test "generated .zshrc.devterm OS label matches DEVTERM_OS" {
  export DEVTERM_OS="linux"
  generate_zshrc
  assert_file_contains "$HOME/.zshrc.devterm" "OS: linux"
}

# ── Theme injection ───────────────────────────────────────────────────────

@test "generated .zshrc.devterm reflects selected theme name" {
  DEVTERM_THEME="latte"
  generate_zshrc
  assert_file_contains "$HOME/.zshrc.devterm" "Latte"
}

# ── Idempotency ───────────────────────────────────────────────────────────

@test "generate_zshrc is idempotent — running twice yields identical .zshrc.devterm" {
  generate_zshrc
  cp "$HOME/.zshrc.devterm" "$HOME/.zshrc.devterm.first"

  generate_zshrc

  diff "$HOME/.zshrc.devterm.first" "$HOME/.zshrc.devterm" || {
    echo "Second run produced a different .zshrc.devterm"; return 1
  }
}

@test "generate_zshrc does not produce empty .zshrc.devterm" {
  generate_zshrc
  [[ -s "$HOME/.zshrc.devterm" ]] || { echo "~/.zshrc.devterm is empty"; return 1; }
}
