#!/usr/bin/env bash
# lib/doctor.sh — devterm health check (devterm --doctor)
#
# Diagnoses the current terminal environment and reports what's installed,
# what's missing, and what might need attention.

# ── Individual checks ──────────────────────────────────────────────────────

# Tool description lookup — portable alternative to declare -A / local -A
# Do NOT use local -A or declare -A — associative arrays require bash 4.0+
_tool_desc() {
  case "$1" in
    zsh)      echo "Shell (required)" ;;
    brew)     echo "Homebrew (macOS)" ;;
    starship) echo "Starship prompt (required)" ;;
    git)      echo "Git (required)" ;;
    fzf)      echo "fzf — fuzzy finder" ;;
    eza)      echo "eza — modern ls" ;;
    bat)      echo "bat — syntax-highlighted cat" ;;
    zoxide)   echo "zoxide — smart cd" ;;
    tmux)     echo "tmux — terminal multiplexer" ;;
    zellij)   echo "zellij — terminal workspace" ;;
    *)        echo "$1" ;;
  esac
}

check_tools() {
  log_header "Tools"

  local all_ok=true
  for tool in zsh starship git brew fzf eza bat zoxide; do
    local desc
    desc="$(_tool_desc "$tool")"

    # brew is macOS-only — skip on Linux
    if [[ "$tool" == "brew" ]] && [[ "${DEVTERM_OS:-macos}" != "macos" ]]; then
      continue
    fi

    if command_exists "$tool"; then
      local version
      version=$("$tool" --version 2>/dev/null | head -1 || echo "installed")
      log_ok "$tool — $desc"
      echo -e "       ${DIM}$version${NC}"
    else
      if [[ "$tool" == "zsh" || "$tool" == "starship" || "$tool" == "git" ]]; then
        log_error "$tool — $desc (REQUIRED — not found)"
        all_ok=false
      else
        log_warn "$tool — $desc (optional — not installed)"
      fi
    fi
  done

  # Explicit boolean check — avoids executing $all_ok as a command
  [[ "$all_ok" == "true" ]]
}

check_config_files() {
  log_header "Configuration files"

  local all_ok=true

  # ~/.zshrc — detect split vs monolithic format
  if [[ -f "$HOME/.zshrc" ]]; then
    if grep -q "Managed by devterm" "$HOME/.zshrc" 2>/dev/null; then
      log_ok "$HOME/.zshrc (split loader)"
      echo -e "       ${DIM}Managed by devterm — sources .zshrc.devterm + .zshrc.local${NC}"
    elif grep -q "Generated by devterm" "$HOME/.zshrc" 2>/dev/null; then
      log_warn "$HOME/.zshrc (old monolithic format)"
      echo -e "       ${DIM}Re-run setup.sh to migrate to split config${NC}"
    else
      log_warn "$HOME/.zshrc exists but was not generated by devterm"
    fi
  else
    log_error "$HOME/.zshrc — not found (run devterm setup to create)"
    all_ok=false
  fi

  # ~/.zshrc.devterm
  if [[ -f "$HOME/.zshrc.devterm" ]]; then
    log_ok "$HOME/.zshrc.devterm"
    echo -e "       ${DIM}devterm-managed config (regenerated each setup)${NC}"
  else
    if grep -q "Managed by devterm" "$HOME/.zshrc" 2>/dev/null; then
      log_error "$HOME/.zshrc.devterm — missing (loader expects it)"
      all_ok=false
    fi
  fi

  # ~/.zshrc.local
  if [[ -f "$HOME/.zshrc.local" ]]; then
    log_ok "$HOME/.zshrc.local"
    echo -e "       ${DIM}Your personal customizations${NC}"
  else
    log_info "$HOME/.zshrc.local — not found (create it for custom config)"
  fi

  # ~/.config/starship.toml
  if [[ -f "$HOME/.config/starship.toml" ]]; then
    log_ok "$HOME/.config/starship.toml"
    if grep -q "catppuccin" "$HOME/.config/starship.toml" 2>/dev/null; then
      local flavor
      flavor=$(grep -m1 "^palette" "$HOME/.config/starship.toml" 2>/dev/null \
        | sed 's/.*catppuccin_//' | tr -d '"' || echo "unknown")
      echo -e "       ${DIM}Catppuccin $flavor${NC}"
    fi
  else
    log_warn "$HOME/.config/starship.toml — not found (Starship will use defaults)"
  fi

  # ~/.oh-my-zsh
  if [[ -d "$HOME/.oh-my-zsh" ]]; then
    log_ok "$HOME/.oh-my-zsh"
  else
    log_error "$HOME/.oh-my-zsh — Oh My Zsh not installed"
    all_ok=false
  fi

  # zsh plugins
  local plugins_base="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins"
  for plugin in zsh-autosuggestions zsh-syntax-highlighting; do
    if [[ -d "$plugins_base/$plugin" ]]; then
      log_ok "$plugin"
    else
      log_warn "$plugin — not installed"
    fi
  done

  [[ "$all_ok" == "true" ]]
}

check_fonts() {
  log_header "Fonts"

  local font_dir
  if [[ "${DEVTERM_OS:-macos}" == "macos" ]]; then
    font_dir="$HOME/Library/Fonts"
  else
    font_dir="$HOME/.local/share/fonts"
  fi

  local found=0
  local meslolgs_fonts=(
    "MesloLGS NF Regular.ttf"
    "MesloLGS NF Bold.ttf"
    "MesloLGS NF Italic.ttf"
    "MesloLGS NF Bold Italic.ttf"
  )

  for font in "${meslolgs_fonts[@]}"; do
    if [[ -f "$font_dir/$font" ]]; then
      log_ok "$font"
      found=$((found + 1))          # avoids ((n++)) == 0 gotcha under set -e
    else
      log_warn "$font — not found in $font_dir"
    fi
  done

  if [[ $found -eq 0 ]]; then
    log_error "MesloLGS NF fonts missing — icons will show as boxes"
    log_info "Fix: re-run devterm setup"
    return 1
  elif [[ $found -lt ${#meslolgs_fonts[@]} ]]; then
    log_warn "Some MesloLGS NF variants missing (${found}/${#meslolgs_fonts[@]} installed)"
    return 0
  fi

  log_ok "All MesloLGS NF fonts installed"
}

check_iterm2() {
  # macOS only
  if [[ "${DEVTERM_OS:-macos}" != "macos" ]]; then
    return 0
  fi

  log_header "iTerm2 (macOS)"

  if [[ "$TERM_PROGRAM" == "iTerm.app" ]]; then
    log_ok "Running inside iTerm2"
  else
    log_warn "Not running in iTerm2 (current: ${TERM_PROGRAM:-unknown})"
    log_info "Some features require iTerm2: https://iterm2.com"
  fi

  local iterm_support="$HOME/Library/Application Support/iTerm2"
  local colors_dir="$iterm_support/ColorPresets"

  if [[ -d "$colors_dir" ]]; then
    local found_count=0
    for theme in mocha latte frappe macchiato; do
      if [[ -f "$colors_dir/catppuccin-${theme}.itermcolors" ]]; then
        log_ok "Color preset: catppuccin-$theme"
        found_count=$((found_count + 1))
      else
        log_warn "Color preset not imported: catppuccin-$theme"
      fi
    done
    if [[ $found_count -eq 0 ]]; then
      log_info "Import: iTerm2 → Preferences → Profiles → Colors → Color Presets → Import"
    fi
  else
    if [[ "$TERM_PROGRAM" == "iTerm.app" ]]; then
      # Running inside iTerm2 but no ColorPresets dir — no presets imported yet
      log_info "No Catppuccin presets imported yet — run './setup.sh --theme mocha' to install"
    else
      log_info "iTerm2 ColorPresets directory not found — iTerm2 may not be installed"
    fi
  fi
}

check_environment() {
  log_header "Environment"

  # OS info
  if [[ "${DEVTERM_OS:-}" == "macos" ]]; then
    local macos_version
    macos_version=$(sw_vers -productVersion 2>/dev/null || echo "unknown")
    local macos_major
    macos_major=$(echo "$macos_version" | cut -d. -f1)
    if [[ "$macos_major" -ge 12 ]] 2>/dev/null; then
      log_ok "macOS $macos_version (supported)"
    else
      log_warn "macOS $macos_version — recommend macOS 12 (Monterey) or later"
    fi
  else
    if [[ -f /etc/os-release ]]; then
      # shellcheck source=/dev/null
      source /etc/os-release
      log_ok "Linux: ${NAME:-unknown} ${VERSION_ID:-}"
    fi
  fi

  # Shell
  local current_shell
  current_shell=$(basename "$SHELL")
  if [[ "$current_shell" == "zsh" ]]; then
    local zsh_version
    zsh_version=$(zsh --version 2>/dev/null | awk '{print $2}')
    log_ok "Login shell: zsh $zsh_version"
  else
    log_warn "Login shell is '$current_shell' — devterm recommends zsh"
    log_info "Fix: chsh -s \$(which zsh)"
  fi

  # Architecture
  log_ok "Architecture: $(uname -m)"

  # Starship config dir
  if [[ -d "$HOME/.config" ]]; then
    log_ok "$HOME/.config directory exists"
  else
    log_warn "$HOME/.config not found — Starship config cannot be placed"
  fi
}

# ── Powerlevel10k leftover check ───────────────────────────────────────────

check_p10k_leftovers() {
  # This check is purely informational — p10k leftovers don't break devterm
  # (because ZSH_THEME="" prevents OMZ from loading p10k), but they can
  # confuse developers wondering if they're still running p10k.

  local found_any=false

  # ~/.p10k.zsh — the p10k config file
  if [[ -f "$HOME/.p10k.zsh" ]]; then
    found_any=true
  fi

  # p10k OMZ theme directory
  if [[ -d "$HOME/.oh-my-zsh/custom/themes/powerlevel10k" ]]; then
    found_any=true
  fi

  # p10k instant prompt cache (one file per user/theme combination)
  local p10k_cache_files
  p10k_cache_files=$(find "${XDG_CACHE_HOME:-$HOME/.cache}" \
    -maxdepth 1 -name "p10k-instant-prompt-*.zsh" 2>/dev/null | wc -l)
  if [[ "$p10k_cache_files" -gt 0 ]]; then
    found_any=true
  fi

  if [[ "$found_any" == "false" ]]; then
    return 0  # nothing to report
  fi

  log_header "Powerlevel10k leftovers"
  echo -e "  ${DIM}devterm uses Starship — p10k files below are no longer active.${NC}"
  echo -e "  ${DIM}They are harmless but can be cleaned up.${NC}"
  echo ""

  if [[ -f "$HOME/.p10k.zsh" ]]; then
    log_warn "$HOME/.p10k.zsh — p10k config (no longer sourced by devterm)"
    echo -e "       ${DIM}Remove: rm ~/.p10k.zsh${NC}"
  fi

  if [[ -d "$HOME/.oh-my-zsh/custom/themes/powerlevel10k" ]]; then
    log_warn "$HOME/.oh-my-zsh/custom/themes/powerlevel10k/ — p10k theme directory"
    echo -e "       ${DIM}Remove: rm -rf ~/.oh-my-zsh/custom/themes/powerlevel10k${NC}"
  fi

  if [[ "$p10k_cache_files" -gt 0 ]]; then
    log_warn "p10k instant-prompt cache ($p10k_cache_files file(s))"
    echo -e "       ${DIM}Remove: rm -f ~/.cache/p10k-instant-prompt-*.zsh${NC}"
  fi

  echo ""
  log_info "To clean all p10k leftovers in one command:"
  echo -e "       ${DIM}rm -f ~/.p10k.zsh ~/.cache/p10k-instant-prompt-*.zsh${NC}"
  echo -e "       ${DIM}rm -rf ~/.oh-my-zsh/custom/themes/powerlevel10k${NC}"
}

# ── Multiplexer check (informational) ─────────────────────────────────

check_multiplexer() {
  local found_any=false

  if command_exists tmux; then
    found_any=true
  fi
  if command_exists zellij; then
    found_any=true
  fi

  if [[ "$found_any" == "false" ]]; then
    return 0
  fi

  log_header "Multiplexer"

  if command_exists tmux; then
    local tmux_ver
    tmux_ver=$(tmux -V 2>/dev/null || echo "installed")
    log_ok "tmux — $(_tool_desc tmux)"
    echo -e "       ${DIM}$tmux_ver${NC}"
    if [[ -f "$HOME/.tmux.conf" ]]; then
      if grep -q "devterm" "$HOME/.tmux.conf" 2>/dev/null; then
        log_ok "$HOME/.tmux.conf (devterm-managed)"
      else
        log_info "$HOME/.tmux.conf exists (not managed by devterm)"
      fi
    else
      log_info "$HOME/.tmux.conf — not found (run setup.sh --multiplexer tmux)"
    fi
  fi

  if command_exists zellij; then
    local zellij_ver
    zellij_ver=$(zellij --version 2>/dev/null || echo "installed")
    log_ok "zellij — $(_tool_desc zellij)"
    echo -e "       ${DIM}$zellij_ver${NC}"
    local zellij_config="$HOME/.config/zellij/config.kdl"
    if [[ -f "$zellij_config" ]]; then
      if grep -q "devterm" "$zellij_config" 2>/dev/null; then
        log_ok "$zellij_config (devterm-managed)"
      else
        log_info "$zellij_config exists (not managed by devterm)"
      fi
    else
      log_info "$zellij_config — not found (run setup.sh --multiplexer zellij)"
    fi
  fi
}

# ── Summary ────────────────────────────────────────────────────────────────

_doctor_summary() {
  local issues="$1"
  echo ""
  echo -e "${MOCHA_MAUVE}${BOLD}══════════════════════════════════════════${NC}"
  if [[ "$issues" -eq 0 ]]; then
    echo -e "  ${MOCHA_GREEN}${BOLD}✓ Everything looks good!${NC}"
  elif [[ "$issues" -le 2 ]]; then
    echo -e "  ${MOCHA_YELLOW}${BOLD}⚠ Minor issues found ($issues)${NC}"
    echo -e "  ${DIM}Review the warnings above and re-run setup if needed.${NC}"
  else
    echo -e "  ${MOCHA_RED}${BOLD}✗ Issues found ($issues)${NC}"
    echo -e "  ${DIM}Run './setup.sh' to repair your devterm installation.${NC}"
  fi
  echo -e "${MOCHA_MAUVE}${BOLD}══════════════════════════════════════════${NC}"
  echo ""
}

# ── Main entry point ───────────────────────────────────────────────────────

doctor() {
  # Detect OS if not already set (e.g. when called via --doctor standalone)
  if [[ -z "${DEVTERM_OS:-}" ]]; then
    case "$OSTYPE" in
      darwin*) DEVTERM_OS="macos" ;;
      linux*)  DEVTERM_OS="linux" ;;
      *)       DEVTERM_OS="unknown" ;;
    esac
    export DEVTERM_OS
  fi

  echo ""
  echo -e "${MOCHA_MAUVE}${BOLD}  devterm doctor — environment health check${NC}"
  echo -e "  ${DIM}$(date '+%Y-%m-%d %H:%M:%S') · Platform: ${DEVTERM_OS}${NC}"
  echo ""

  local issues=0

  # Use arithmetic assignment to avoid the ((n++)) == 0 false-failure under set -e
  check_environment  || issues=$((issues + 1))
  check_tools        || issues=$((issues + 1))
  check_config_files || issues=$((issues + 1))
  check_fonts        || issues=$((issues + 1))
  check_iterm2
  check_multiplexer          # informational only — never increments issues
  check_p10k_leftovers       # informational only — never increments issues

  _doctor_summary "$issues"

  return $(( issues > 0 ? 1 : 0 ))
}
