#!/usr/bin/env bash
# lib/starship.sh — Starship prompt installation and configuration

STARSHIP_CONFIG_DIR="$HOME/.config"
STARSHIP_CONFIG_FILE="$STARSHIP_CONFIG_DIR/starship.toml"

install_starship() {
  log_step "Installing Starship prompt"

  if command_exists starship; then
    local version
    version=$(starship --version 2>/dev/null | head -1)
    log_skip "Starship ($version)"
    _install_starship_config
    return 0
  fi

  if [[ "$DEVTERM_OS" == "macos" ]]; then
    log_info "Installing Starship via Homebrew..."
    if brew install starship &>/dev/null; then
      log_ok "Starship installed"
    else
      log_error "Failed to install Starship via Homebrew"
      return 1
    fi
  else
    # Linux: use the official installer script
    log_info "Installing Starship via official installer..."
    if curl -fsSL https://starship.rs/install.sh | sh -s -- --yes &>/dev/null; then
      log_ok "Starship installed"
      # Ensure ~/.local/bin is in PATH for current session
      export PATH="$HOME/.local/bin:$PATH"
    else
      log_error "Failed to install Starship. Check your internet connection."
      return 1
    fi
  fi

  _install_starship_config
}

_install_starship_config() {
  # Resolve project root: prefer the exported $DEVTERM_ROOT, fall back to
  # path-relative computation so the function works when sourced standalone.
  local root="${DEVTERM_ROOT:-$(dirname "$(dirname "${BASH_SOURCE[0]}")")}"
  local config_src="${root}/config/starship-${DEVTERM_THEME}.toml"

  mkdir -p "$STARSHIP_CONFIG_DIR"

  if [[ ! -f "$config_src" ]]; then
    log_warn "No config found for theme '${DEVTERM_THEME}' — falling back to mocha"
    config_src="${root}/config/starship-mocha.toml"
  fi

  if [[ -f "$STARSHIP_CONFIG_FILE" ]]; then
    # Only overwrite if it was generated by devterm
    if grep -q "devterm" "$STARSHIP_CONFIG_FILE" 2>/dev/null; then
      cp "$config_src" "$STARSHIP_CONFIG_FILE"
      log_ok "Starship config updated (~/.config/starship.toml)"
    else
      log_skip "$HOME/.config/starship.toml (existing custom config preserved)"
      log_info "To use devterm theme: cp $config_src ~/.config/starship.toml"
    fi
    return 0
  fi

  cp "$config_src" "$STARSHIP_CONFIG_FILE"
  log_ok "Starship config installed — Catppuccin $(_capitalize "$DEVTERM_THEME") (~/.config/starship.toml)"
  log_info "Customize anytime: edit ~/.config/starship.toml"
}
