#!/usr/bin/env bash
# lib/zshrc.sh — Generate optimized ~/.zshrc

ZSHRC="$HOME/.zshrc"

generate_zshrc() {
  log_step "Configuring ~/.zshrc"

  # Backup existing config
  backup_file "$ZSHRC"

  local theme="${DEVTERM_THEME:-mocha}"
  local os="${DEVTERM_OS:-macos}"

  # Pre-compute display strings BEFORE the heredoc.
  # ${var^} (capitalize first letter) requires bash 4.0+ — it is NOT available
  # in macOS built-in bash 3.2 and causes "bad substitution" inside heredocs.
  local theme_cap
  theme_cap="$(_capitalize "$theme")"

  # Build platform-specific plugin list:
  # The OMZ 'macos' plugin only exists on macOS — including it on Linux
  # causes OMZ to print a warning on every shell start.
  local omz_plugins
  if [[ "$os" == "macos" ]]; then
    omz_plugins="git
  zsh-autosuggestions
  zsh-syntax-highlighting
  fzf
  macos
  docker
  kubectl
  sudo"
  else
    omz_plugins="git
  zsh-autosuggestions
  zsh-syntax-highlighting
  fzf
  docker
  kubectl
  sudo"
  fi

  cat > "$ZSHRC" << ZSHRC_EOF
# =============================================================================
# ~/.zshrc — Generated by devterm (https://github.com/c0x12c/devterm-kit)
# Theme: Catppuccin ${theme_cap}  |  Stack: Oh My Zsh + Starship  |  OS: ${os}
# Regenerate: devterm --reconfigure
# =============================================================================

# =============================================================================
# Oh My Zsh — plugin framework (Starship handles the prompt)
# =============================================================================
export ZSH="\$HOME/.oh-my-zsh"

# Disable OMZ theme — Starship is the prompt
ZSH_THEME=""

plugins=(
  ${omz_plugins}
)

source "\$ZSH/oh-my-zsh.sh"

# =============================================================================
# Starship prompt
# =============================================================================
if command -v starship &>/dev/null; then
  eval "\$(starship init zsh)"
fi

# =============================================================================
# CLI Tool Aliases
# =============================================================================

# eza — modern ls with icons
if command -v eza &>/dev/null; then
  alias ls="eza --icons --group-directories-first"
  alias ll="eza -la --icons --group-directories-first --git"
  alias la="eza -a --icons --group-directories-first"
  alias lt="eza --tree --icons --level=2"
  alias ltt="eza --tree --icons --level=3"
fi

# bat — cat with syntax highlighting
if command -v bat &>/dev/null; then
  alias cat="bat --theme=Catppuccin-Mocha"
  export MANPAGER="sh -c 'col -bx | bat -l man -p --theme=Catppuccin-Mocha'"
  export BAT_THEME="Catppuccin-Mocha"
fi

# zoxide — smart cd
if command -v zoxide &>/dev/null; then
  eval "\$(zoxide init zsh)"
  alias j="z"    # jump: j project-name
fi

# fzf — fuzzy finder
if command -v fzf &>/dev/null; then
  export FZF_DEFAULT_OPTS="
    --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8
    --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc
    --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8
    --height 40% --layout=reverse --border --bind='ctrl-/:toggle-preview'"
  [[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh
fi

# =============================================================================
# Git Aliases
# =============================================================================
alias g="git"
alias gs="git status"
alias ga="git add"
alias gaa="git add -A"
alias gc="git commit"
alias gcm="git commit -m"
alias gp="git push"
alias gpl="git pull"
alias gl="git log --oneline --graph --decorate --color"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gd="git diff"
alias gds="git diff --staged"
alias grb="git rebase"
alias gst="git stash"
alias gstp="git stash pop"

# =============================================================================
# Navigation
# =============================================================================
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias ~="cd ~"

# =============================================================================
# Gradle / Kotlin (Spartan stack)
# =============================================================================
alias gw="./gradlew"
alias gwb="./gradlew build"
alias gwt="./gradlew test"
alias gwk="./gradlew ktlintFormat"
alias gwc="./gradlew ktlintCheck"
alias gwr="./gradlew :app:api-application:run -Dmicronaut.environments=local"

# =============================================================================
# Docker
# =============================================================================
alias d="docker"
alias dc="docker compose"
alias dcu="docker compose up -d"
alias dcd="docker compose down"
alias dcl="docker compose logs -f"
alias dcr="docker compose restart"
alias dps="docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'"

# =============================================================================
# Misc
# =============================================================================
alias reload="source ~/.zshrc && echo '✓ .zshrc reloaded'"
alias zshrc="\${EDITOR:-nano} ~/.zshrc"
alias ip="ipconfig getifaddr en0 2>/dev/null || hostname -I | awk '{print \$1}'"
# macOS-only aliases
if [[ "\$(uname)" == "Darwin" ]]; then
  alias flush-dns="sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder"
  alias show-files="defaults write com.apple.finder AppleShowAllFiles YES && killall Finder"
  alias hide-files="defaults write com.apple.finder AppleShowAllFiles NO && killall Finder"
fi

# =============================================================================
# Environment
# =============================================================================
export EDITOR="code"
export VISUAL="code"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export TERM=xterm-256color

# PATH — local binaries (Starship on Linux installs here)
export PATH="\$HOME/.local/bin:\$PATH"

# Homebrew (macOS — Apple Silicon + Intel)
if [[ -f /opt/homebrew/bin/brew ]]; then
  eval "\$(/opt/homebrew/bin/brew shellenv)"
elif [[ -f /usr/local/bin/brew ]]; then
  eval "\$(/usr/local/bin/brew shellenv)"
fi

# Node / NVM
export NVM_DIR="\$HOME/.nvm"
[[ -s "\$NVM_DIR/nvm.sh" ]] && source "\$NVM_DIR/nvm.sh"
[[ -s "\$NVM_DIR/bash_completion" ]] && source "\$NVM_DIR/bash_completion"

# Java / SDKMAN
[[ -s "\$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "\$HOME/.sdkman/bin/sdkman-init.sh"

# Python / pyenv
if command -v pyenv &>/dev/null; then
  export PYENV_ROOT="\$HOME/.pyenv"
  export PATH="\$PYENV_ROOT/bin:\$PATH"
  eval "\$(pyenv init -)"
fi
ZSHRC_EOF

  log_ok "$HOME/.zshrc generated"
  log_info "Customize: edit ~/.zshrc or run 'devterm --reconfigure'"
}
