#!/usr/bin/env bash
# lib/zshrc.sh — Generate split .zshrc config (loader + devterm + local)
#
# File structure:
#   ~/.zshrc          Thin loader (sources .zshrc.devterm + .zshrc.local)
#   ~/.zshrc.devterm  Managed by devterm — regenerated every setup.sh run
#   ~/.zshrc.local    User's custom config — NEVER touched by devterm

ZSHRC="$HOME/.zshrc"
ZSHRC_DEVTERM="$HOME/.zshrc.devterm"
ZSHRC_LOCAL="$HOME/.zshrc.local"

# ── Migration scenario detection ─────────────────────────────────────────

# Sets ZSHRC_SCENARIO to A, B, C, or D
_detect_zshrc_scenario() {
  if [[ ! -f "$ZSHRC" ]]; then
    ZSHRC_SCENARIO="A"  # Fresh install — no .zshrc at all
  elif grep -q "Managed by devterm" "$ZSHRC" 2>/dev/null; then
    ZSHRC_SCENARIO="C"  # Already migrated to split format
  elif grep -q "Generated by devterm" "$ZSHRC" 2>/dev/null; then
    ZSHRC_SCENARIO="B"  # Old monolithic devterm .zshrc
  else
    ZSHRC_SCENARIO="D"  # Non-devterm .zshrc (user's own config)
  fi
}

# ── Migration handler ─────────────────────────────────────────────────────

_handle_migration() {
  case "$ZSHRC_SCENARIO" in
    A)
      # Fresh install — create all 3 files
      _write_loader
      _write_zshrc_local_template
      ;;
    B)
      # Old monolithic devterm .zshrc — backup and migrate
      backup_file "$ZSHRC"
      _write_loader
      _write_zshrc_local_template
      log_info "Migrated to split config. Move custom additions to ~/.zshrc.local"
      ;;
    C)
      # Already migrated — only regenerate .zshrc.devterm
      # Touch nothing else
      ;;
    D)
      # Non-devterm .zshrc — preserve user config
      if [[ ! -f "$ZSHRC_LOCAL" ]]; then
        # Move existing .zshrc to .zshrc.local (preserve user config!)
        mv "$ZSHRC" "$ZSHRC_LOCAL"
        log_info "Moved existing ~/.zshrc → ~/.zshrc.local (your config is preserved)"
      else
        # .zshrc.local already exists — don't clobber it
        backup_file "$ZSHRC"
        log_info "Existing ~/.zshrc backed up (your ~/.zshrc.local was kept)"
      fi
      _write_loader
      ;;
  esac
}

# ── Loader file (~/.zshrc) ────────────────────────────────────────────────

_write_loader() {
  cat > "$ZSHRC" << 'LOADER_EOF'
# =============================================================================
# ~/.zshrc — Managed by devterm (https://github.com/c0x12c/devterm-kit)
# DO NOT edit this file — it is regenerated during migration.
#
# Your config goes in:  ~/.zshrc.local   (never overwritten by devterm)
# devterm-managed:      ~/.zshrc.devterm (regenerated every setup.sh run)
# =============================================================================

# Load devterm-managed config
[[ -f "$HOME/.zshrc.devterm" ]] && source "$HOME/.zshrc.devterm"

# Load your personal customizations (safe — never overwritten)
[[ -f "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"
LOADER_EOF
}

# ── User local template (~/.zshrc.local) ──────────────────────────────────

_write_zshrc_local_template() {
  # Only create if it doesn't exist — NEVER overwrite
  [[ -f "$ZSHRC_LOCAL" ]] && return 0

  cat > "$ZSHRC_LOCAL" << 'LOCAL_EOF'
# =============================================================================
# ~/.zshrc.local — Your personal shell customizations
# This file is NEVER overwritten by devterm. Put your custom config here.
#
# Examples:
#   export MY_API_KEY="xxx"
#   alias myproject="cd ~/Work/my-project"
#   source "$HOME/.cargo/env"
# =============================================================================
LOCAL_EOF
}

# ── Devterm managed config (~/.zshrc.devterm) ─────────────────────────────

_generate_zshrc_devterm() {
  local theme="${DEVTERM_THEME:-mocha}"
  local os="${DEVTERM_OS:-macos}"

  local theme_cap
  theme_cap="$(_capitalize "$theme")"

  # Build platform-specific plugin list
  local omz_plugins
  if [[ "$os" == "macos" ]]; then
    omz_plugins="git
  zsh-autosuggestions
  zsh-syntax-highlighting
  fzf
  macos
  docker
  kubectl
  sudo"
  else
    omz_plugins="git
  zsh-autosuggestions
  zsh-syntax-highlighting
  fzf
  docker
  kubectl
  sudo"
  fi

  cat > "$ZSHRC_DEVTERM" << ZSHRC_EOF
# =============================================================================
# ~/.zshrc.devterm — Generated by devterm (https://github.com/c0x12c/devterm-kit)
# Theme: Catppuccin ${theme_cap}  |  Stack: Oh My Zsh + Starship  |  OS: ${os}
# DO NOT edit — this file is regenerated every setup.sh run.
# Your custom config goes in: ~/.zshrc.local
# =============================================================================

# =============================================================================
# Environment (loaded early — PATH and tools need to be available first)
# =============================================================================
export EDITOR="code"
export VISUAL="code"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export TERM=xterm-256color

# PATH — local binaries (Starship on Linux installs here)
export PATH="\$HOME/.local/bin:\$PATH"

# Homebrew (macOS — Apple Silicon + Intel)
if [[ -f /opt/homebrew/bin/brew ]]; then
  eval "\$(/opt/homebrew/bin/brew shellenv)"
elif [[ -f /usr/local/bin/brew ]]; then
  eval "\$(/usr/local/bin/brew shellenv)"
fi

# =============================================================================
# Oh My Zsh — plugin framework (Starship handles the prompt)
# =============================================================================
export ZSH="\$HOME/.oh-my-zsh"

# Disable OMZ theme — Starship is the prompt
ZSH_THEME=""

plugins=(
  ${omz_plugins}
)

source "\$ZSH/oh-my-zsh.sh"

# =============================================================================
# Starship prompt
# =============================================================================
if command -v starship &>/dev/null; then
  eval "\$(starship init zsh)"
fi

# =============================================================================
# CLI Tool Aliases
# =============================================================================

# eza — modern ls with icons
if command -v eza &>/dev/null; then
  alias ls="eza --icons --group-directories-first"
  alias ll="eza -la --icons --group-directories-first --git"
  alias la="eza -a --icons --group-directories-first"
  alias lt="eza --tree --icons --level=2"
  alias ltt="eza --tree --icons --level=3"
fi

# bat — cat with syntax highlighting
if command -v bat &>/dev/null; then
  alias cat="bat --theme=Catppuccin-Mocha"
  export MANPAGER="sh -c 'col -bx | bat -l man -p --theme=Catppuccin-Mocha'"
  export BAT_THEME="Catppuccin-Mocha"
fi

# zoxide — smart cd
if command -v zoxide &>/dev/null; then
  eval "\$(zoxide init zsh)"
  alias j="z"    # jump: j project-name
fi

# fzf — fuzzy finder
if command -v fzf &>/dev/null; then
  export FZF_DEFAULT_OPTS="
    --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8
    --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc
    --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8
    --height 40% --layout=reverse --border --bind='ctrl-/:toggle-preview'"
  [[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh
fi

# =============================================================================
# Git Aliases
# =============================================================================
alias g="git"
alias gs="git status"
alias ga="git add"
alias gaa="git add -A"
alias gc="git commit"
alias gcm="git commit -m"
alias gp="git push"
alias gpl="git pull"
alias gl="git log --oneline --graph --decorate --color"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gd="git diff"
alias gds="git diff --staged"
alias grb="git rebase"
alias gst="git stash"
alias gstp="git stash pop"

# =============================================================================
# Navigation
# =============================================================================
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias ~="cd ~"

# =============================================================================
# Gradle / Kotlin (Spartan stack)
# =============================================================================
alias gw="./gradlew"
alias gwb="./gradlew build"
alias gwt="./gradlew test"
alias gwk="./gradlew ktlintFormat"
alias gwc="./gradlew ktlintCheck"
alias gwr="./gradlew :app:api-application:run -Dmicronaut.environments=local"

# =============================================================================
# Docker
# =============================================================================
alias d="docker"
alias dc="docker compose"
alias dcu="docker compose up -d"
alias dcd="docker compose down"
alias dcl="docker compose logs -f"
alias dcr="docker compose restart"
alias dps="docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'"

# =============================================================================
# Misc
# =============================================================================
alias reload="source ~/.zshrc && echo '✓ .zshrc reloaded'"
alias zshrc="\${EDITOR:-nano} ~/.zshrc.local"
alias ip="ipconfig getifaddr en0 2>/dev/null || hostname -I | awk '{print \$1}'"
# macOS-only aliases
if [[ "\$(uname)" == "Darwin" ]]; then
  alias flush-dns="sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder"
  alias show-files="defaults write com.apple.finder AppleShowAllFiles YES && killall Finder"
  alias hide-files="defaults write com.apple.finder AppleShowAllFiles NO && killall Finder"
fi

# =============================================================================
# devterm update check — silent, cached 24h, background
# =============================================================================
_devterm_update_check() {
  local DEVTERM_DIR="\${DEVTERM_DIR:-\$HOME/.devterm}"
  local cache_file="\$HOME/.cache/devterm-update-check"
  local cache_max=86400  # 24 hours

  # Skip if no devterm install or no git
  [[ -f "\$DEVTERM_DIR/VERSION" ]] || return 0
  command -v git &>/dev/null || return 0

  # Skip if cache is fresh
  if [[ -f "\$cache_file" ]]; then
    local now cache_mtime age
    now=\$(date +%s)
    if [[ "\$(uname)" == "Darwin" ]]; then
      cache_mtime=\$(stat -f %m "\$cache_file" 2>/dev/null || echo 0)
    else
      cache_mtime=\$(stat -c %Y "\$cache_file" 2>/dev/null || echo 0)
    fi
    age=\$((now - cache_mtime))
    [[ \$age -lt \$cache_max ]] && return 0
  fi

  # Run check in background — never block shell startup
  (
    mkdir -p "\$HOME/.cache"
    local local_ver remote_ver
    local_ver=\$(cat "\$DEVTERM_DIR/VERSION" 2>/dev/null)
    remote_ver=\$(git -C "\$DEVTERM_DIR" ls-remote --tags origin 2>/dev/null \
      | awk '{print \$2}' | sed 's|refs/tags/v||' | sort -V | tail -1)

    # Write cache regardless — prevents re-checking on failure
    echo "\$remote_ver" > "\$cache_file" 2>/dev/null

    if [[ -n "\$remote_ver" && "\$remote_ver" != "\$local_ver" ]]; then
      # Compare versions: only notify if remote is newer
      local higher
      higher=\$(printf '%s\n%s' "\$local_ver" "\$remote_ver" | sort -V | tail -1)
      if [[ "\$higher" == "\$remote_ver" && "\$higher" != "\$local_ver" ]]; then
        echo "\$remote_ver" > "\$cache_file"
      else
        echo "" > "\$cache_file"
      fi
    else
      echo "" > "\$cache_file"
    fi
  ) &>/dev/null &
  disown

  # Show notification from previous check
  if [[ -f "\$cache_file" ]]; then
    local cached_ver
    cached_ver=\$(cat "\$cache_file" 2>/dev/null)
    if [[ -n "\$cached_ver" ]]; then
      local local_ver
      local_ver=\$(cat "\$DEVTERM_DIR/VERSION" 2>/dev/null)
      echo "  ⬆ devterm \$cached_ver available (current: \$local_ver) — run 'devterm update'"
    fi
  fi
}
_devterm_update_check

# =============================================================================
# devterm CLI — run 'devterm tips', 'devterm doctor', 'devterm update'
# =============================================================================
devterm() {
  local DEVTERM_DIR="\${DEVTERM_DIR:-\$HOME/.devterm}"

  case "\${1:-}" in
    tips|cheatsheet)
      if [[ -f "\$DEVTERM_DIR/lib/tips.sh" ]]; then
        source "\$DEVTERM_DIR/lib/tips.sh" && show_tips
      else
        echo "devterm not found at \$DEVTERM_DIR — reinstall with:"
        echo "  curl -fsSL https://raw.githubusercontent.com/c0x12c/devterm-kit/master/install.sh | bash"
      fi
      ;;
    doctor)
      if [[ -f "\$DEVTERM_DIR/setup.sh" ]]; then
        bash "\$DEVTERM_DIR/setup.sh" --doctor
      else
        echo "devterm not found at \$DEVTERM_DIR"
      fi
      ;;
    update)
      if [[ -f "\$DEVTERM_DIR/setup.sh" ]]; then
        local old_ver new_ver
        old_ver=\$(cat "\$DEVTERM_DIR/VERSION" 2>/dev/null || echo "?")
        (cd "\$DEVTERM_DIR" && git fetch --quiet origin && git reset --hard origin/master --quiet) || { echo "Update failed"; return 1; }
        new_ver=\$(cat "\$DEVTERM_DIR/VERSION" 2>/dev/null || echo "?")
        # Clear update notification cache
        rm -f "\$HOME/.cache/devterm-update-check"
        if [[ "\$old_ver" == "\$new_ver" ]]; then
          echo "✓ devterm v\$new_ver — already up to date"
        else
          echo "✓ devterm updated: v\$old_ver → v\$new_ver"
          echo "  Run 'devterm tips' to see what's new"
        fi
      else
        echo "devterm not found at \$DEVTERM_DIR"
      fi
      ;;
    restore)
      local backups
      backups=(\$(ls -t "\$HOME"/.zshrc.backup.* 2>/dev/null))
      if [[ \${#backups[@]} -eq 0 ]]; then
        echo "No backups found."
        return 0
      fi
      echo "Available backups (newest first):"
      echo ""
      local i
      for i in "\${!backups[@]}"; do
        local ts=\$(echo "\${backups[\$i]}" | grep -o '[0-9]\\{8\\}_[0-9]\\{6\\}')
        local d="\${ts:0:4}-\${ts:4:2}-\${ts:6:2} \${ts:9:2}:\${ts:11:2}"
        local size=\$(wc -c < "\${backups[\$i]}" | tr -d ' ')
        printf "  %d) %s  (%s bytes)\\n" \$((i + 1)) "\$d" "\$size"
      done
      echo ""
      echo -n "Restore which backup? [1-\${#backups[@]}, or q to cancel]: "
      local choice
      read -r choice < /dev/tty
      if [[ "\$choice" == "q" || -z "\$choice" ]]; then
        echo "Cancelled."
        return 0
      fi
      if [[ "\$choice" -ge 1 && "\$choice" -le \${#backups[@]} ]] 2>/dev/null; then
        local selected="\${backups[\$((choice - 1))]}"
        cp "\$HOME/.zshrc" "\$HOME/.zshrc.before-restore.\$(date +%Y%m%d_%H%M%S)"
        cp "\$selected" "\$HOME/.zshrc"
        echo "✓ Restored from \$selected"
        echo "  Run 'source ~/.zshrc' or open a new terminal to apply."
      else
        echo "Invalid choice."
      fi
      ;;
    version|-v|--version)
      echo "devterm v\$(cat "\$DEVTERM_DIR/VERSION" 2>/dev/null || echo "unknown")"
      ;;
    help|"")
      echo "Usage: devterm <command>"
      echo ""
      echo "Commands:"
      echo "  tips      Show cheat sheet — what changed and how to use it"
      echo "  doctor    Diagnose your devterm installation"
      echo "  update    Pull latest devterm from GitHub"
      echo "  restore   Restore your previous ~/.zshrc from backup"
      echo "  version   Show installed version"
      echo "  help      Show this help"
      ;;
    *)
      echo "Unknown command: \$1 — run 'devterm help' for usage"
      ;;
  esac
}

# Node / NVM
export NVM_DIR="\$HOME/.nvm"
[[ -s "\$NVM_DIR/nvm.sh" ]] && source "\$NVM_DIR/nvm.sh"
[[ -s "\$NVM_DIR/bash_completion" ]] && source "\$NVM_DIR/bash_completion"

# Java / SDKMAN
[[ -s "\$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "\$HOME/.sdkman/bin/sdkman-init.sh"

# Python / pyenv
if command -v pyenv &>/dev/null; then
  export PYENV_ROOT="\$HOME/.pyenv"
  export PATH="\$PYENV_ROOT/bin:\$PATH"
  eval "\$(pyenv init -)"
fi
ZSHRC_EOF
}

# ── Main entry point ──────────────────────────────────────────────────────

generate_zshrc() {
  log_step "Configuring shell config"

  _detect_zshrc_scenario

  case "$ZSHRC_SCENARIO" in
    A) log_info "Fresh install — creating split config" ;;
    B) log_info "Migrating old monolithic .zshrc to split format" ;;
    C) log_info "Split config detected — regenerating ~/.zshrc.devterm" ;;
    D) log_info "Existing .zshrc detected — preserving in ~/.zshrc.local" ;;
  esac

  _handle_migration

  # Backup .zshrc.devterm before regenerating (if it exists)
  backup_file "$ZSHRC_DEVTERM"

  _generate_zshrc_devterm

  log_ok "$HOME/.zshrc.devterm generated"
  log_info "Custom config: edit ~/.zshrc.local — run 'devterm tips' for cheat sheet"
}
